{"errorMessage": "Key ':1:event_seq_num' not found", "traceback": "Traceback (most recent call last):\n\n  File \"/usr/local/lib/python2.7/dist-packages/tastypie/resources.py\", line 192, in wrapper\n    response = callback(request, *args, **kwargs)\n\n  File \"/home/oqgpo/projects/kurre/core/api/resources_v3.py\", line 529, in dispatch_detail_device_states\n    return device_states_resource.dispatch_detail(request, **kwargs)\n\n  File \"/home/oqgpo/projects/kurre/core/api/resources_v3.py\", line 663, in dispatch_detail\n    return super(DeviceStateValueResource, self).dispatch_detail(request, **kwargs)\n\n  File \"/usr/local/lib/python2.7/dist-packages/tastypie/resources.py\", line 406, in dispatch_detail\n    return self.dispatch('detail', request, **kwargs)\n\n  File \"/usr/local/lib/python2.7/dist-packages/tastypie/resources.py\", line 427, in dispatch\n    response = method(request, **kwargs)\n\n  File \"/usr/local/lib/python2.7/dist-packages/tastypie/resources.py\", line 1332, in patch_detail\n    self.update_in_place(request, bundle, deserialized)\n\n  File \"/usr/local/lib/python2.7/dist-packages/tastypie/resources.py\", line 1346, in update_in_place\n    return self.obj_update(original_bundle, request=request, pk=original_bundle.obj.pk)\n\n  File \"/usr/local/lib/python2.7/dist-packages/tastypie/resources.py\", line 1824, in obj_update\n    bundle.obj.save()\n\n  File \"/home/oqgpo/projects/kurre/core/models.py\", line 551, in save\n    self.value))\n\n  File \"/home/oqgpo/projects/kurre/events/event.py\", line 33, in add_event\n    cache.incr('event_seq_num')\n\n  File \"/usr/lib/python2.7/dist-packages/django/core/cache/backends/memcached.py\", line 96, in incr\n    raise ValueError(\"Key '%s' not found\" % key)\n\nValueError: Key ':1:event_seq_num' not found\n"}